const initialState = {
    tiles: [ // hero tiles
        {
            id: 'NT2',
            location: 'NT',
            los: ['purple'],
            unit: null,
            movement: true,
        },
        {
            id: 'NT3',
            location: 'NT',
            los: ['purple'],
            unit: null,
            movement: true,
        },
        {
            id: 'NT5',
            location: 'NT',
            los: ['purple', 'yellow'],
            unit: null,
            movement: true,
        },
        {
            id: 'NT6',
            location: 'NT',
            los: ['purple', 'orange'],
            unit: null,
            movement: true,
        },
        {
            id: 'ST2',
            location: 'ST',
            los: ['green'],
            unit: null,
            movement: true,
        },
        {
            id: 'ST4',
            location: 'ST',
            los: ['green'],
            unit: null,
            movement: true,
        },
        {
            id: 'ST5',
            location: 'ST',
            los: ['green', 'orange'],
            unit: null,
            movement: true,
        },
        {
            id: 'ST6',
            location: 'ST',
            los: ['green', 'yellow'],
            unit: null,
            movement: true,
        },
        {
            id: 'K1',
            location: 'K',
            los: ['orange'],
            unit: null,
            movement: true,
        },
        {
            id: 'K2',
            location: 'K',
            los: ['orange'],
            unit: null,
            movement: true,
        },
        {
            id: 'K3',
            location: 'K',
            los: ['orange', 'green'],
            unit: null,
            movement: true,
        },
        {
            id: 'K4',
            location: 'K',
            los: ['orange', 'purple'],
            unit: null,
            movement: true,
        },
        {
            id: 'GH1',
            location: 'GH',
            los: ['purple'],
            unit: null,
            movement: true,
        },
        {
            id: 'GH2',
            location: 'GH',
            los: ['green'],
            unit: null,
            movement: true,
        },
        {
            id: 'GH3',
            location: 'GH',
            los: ['yellow'],
            unit: null,
            movement: true,
        },
        {
            id: 'GH4',
            location: 'GH',
            los: ['yellow'],
            unit: null,
            movement: true,
        },
        {
            id: 'G1',
            location: 'G',
            los: ['yellow', 'black'],
            unit: null,
            movement: true,
        },
        {
            id: 'G2',
            location: 'G',
            los: ['yellow', 'black'],
            unit: 'pollack',
            movement: true,
        },
        {
            id: 'G3',
            location: 'G',
            los: ['black'],
            unit: 'clemenceau',
            movement: true,
        },
        {
            id: 'G4',
            location: 'G',
            los: ['black'],
            unit: 'basse',
            movement: true,
            armament: {
                name: 'M13/A4',
                attack: 2,
                suppress: 3,
            }
        }, 
        {
            id: 'BJ1',
            location: 'BJ',
            los: [],
            unit: 'steiner',
            movement: true,
            armament: {
                name: '76mm (Load)',
                load: true,
            },
        },
        {
            id: 'BJ2',
            location: 'BJ',
            los: ['black'],
            unit: null,
            movement: true,
            armament: {
                name: '76mm (Fire)',
                attack: 4,
                suppress: 7,
                loaded: false,
            },
        },
        {
            id: 'BJ3',
            location: 'BJ',
            los: ['black'],
            unit: 'rushford',
            movement: true,
            armament: {
                name: 'M2HB',
                attack: 2,
                suppress: 4,
            },
        },
        {
            id: 'BJ4',
            location: 'BJ',
            los: ['black'],
            unit: null,
            movement: true,
            armament: {
                name: 'M1919A4',
                attack: 2,
                suppress: 3,
            },
        },
        {
            id: 'C1',
            location: 'C',
            los: [],
            unit: 'gamelin',
            movement: false,
        },
        {
            id: 'C2',
            location: 'C',
            los: [],
            unit: null,
            movement: false,
        },
        {
            id: 'C3',
            location: 'C',
            los: [],
            unit: 'rocque',
            movement: false,
        },
        {
            id: 'C4',
            location: 'C',
            los: [],
            unit: 'reynaud',
            movement: false,
        },
        {
            id: 'C5',
            location: 'C',
            los: [],
            unit: 'borotra',
            movement: false,
        },
        {
            id: 'D1',
            location: 'D',
            los: [],
            unit: null, // basse
            movement: false,
        },
        {
            id: 'D2',
            location: 'D',
            los: [],
            unit: 'lee',
            movement: false,
        },
        {
            id: 'D3',
            location: 'D',
            los: [],
            unit: 'worsham',
            movement: false,
        },
        {
            id: 'D4',
            location: 'D',
            los: [],
            unit: null, // pollack
            movement: false,
        },
        {
            id: 'D5',
            location: 'D',
            los: [],
            unit: 'sutton',
            movement: false,
        },
        {
            id: 'D6',
            location: 'D',
            los: [],
            unit: 'petrukovich',
            movement: false,
        },
        {
            id: 'D7',
            location: 'D',
            los: [],
            unit: null, // steiner
            movement: false,
        },
        {
            id: 'D8',
            location: 'D',
            los: [],
            unit: 'szymczyk',
            movement: false,
        },
        {
            id: 'D9',
            location: 'D',
            los: [],
            unit: 'rushford',
            movement: false,
        },
        {
            id: 'D10',
            location: 'D',
            los: [],
            unit: 'mchaley',
            movement: false,
        },
        {
            id: 'D11',
            location: 'D',
            los: [],
            unit: 'schrader',
            movement: false,
        },
        {
            id: 'D12',
            location: 'D',
            los: [],
            unit: 'gangl',
            movement: false,
        },
        {
            id: 'D13',
            location: 'D',
            los: [],
            unit: 'dietrich',
            movement: false,
        },
        {
            id: 'D14',
            location: 'D',
            los: [],
            unit: 'hockel',
            movement: false,
        },
        {
            id: 'D15',
            location: 'D',
            los: [],
            unit: 'blechschmidt',
            movement: false,
        },
        {
            id: 'D16',
            location: 'D',
            los: [],
            unit: 'rifleman1',
            movement: false,
        },
        {
            id: 'D17',
            location: 'D',
            los: [],
            unit: 'rifleman2',
            movement: false,
        },
        {
            id: 'D18',
            location: 'D',
            los: [],
            unit: 'rifleman3',
            movement: false,
        },
        {
            id: 'D19',
            location: 'D',
            los: [],
            unit: 'rifleman4',
            movement: false,
        },
        {
            id: 'D20',
            location: 'D',
            los: [],
            unit: 'rifleman5',
            movement: false,
        },
        {
            id: 'R1',
            location: 'R',
            los: [],
            unit: 'wegscheider',
            movement: false,
        },
        {
            id: 'R2',
            location: 'R',
            los: [],
            unit: 'linson',
            movement: false,
        },
        {
            id: 'R3',
            location: 'R',
            los: [],
            unit: 'waltl',
            movement: false,
        },
    ],
};

const reducer = (state = initialState, { type, payload }) => {
    switch (type) {
    case 'UPDATE_TILES':
        return {
            ...state,
            tiles: [...payload],
        };
    default:
        return state;
    }
};

export default reducer;
