const initialState = {
    allies: {
        basse: {
            id: 'basse',
            name: 'Basse',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            commander: true,
            tanker: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: true,
            casualty: false,
            tile: 'G4',
        },
        lee: {
            id: 'lee',
            name: 'Lee',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            commander: true,
            tanker: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        worsham: {
            id: 'worsham',
            name: 'Worsham',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        pollack: {
            id: 'pollack',
            name: 'Pollack',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 2,
            suppress: 3,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'G2',
        },
        sutton: {
            id: 'sutton',
            name: 'Sutton',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        petrukovich: {
            id: 'petrukovich',
            name: 'Petrukovich',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        steiner: {
            id: 'steiner',
            name: 'Steiner',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            tanker: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'BJ1',
        },
        szymczyk: {
            id: 'szymczyk',
            name: 'Szymczyk',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            tanker: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        rushford: {
            id: 'rushford',
            name: 'Rushford',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            tanker: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        mchaley: {
            id: 'mchaley',
            name: 'McHaley',
            nationality: 'USA',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            tanker: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        schrader: {
            id: 'schrader',
            name: 'Schrader',
            nationality: 'SS',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            commander: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        gangl: {
            id: 'gangl',
            name: 'Gangl',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 2,
            commander: true,
            officer: true,
            sacrifice: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        dietrich: {
            id: 'dietrich',
            name: 'Dietrich',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            officer: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        hockel: {
            id: 'hockel',
            name: 'Hockel',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            officer: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: true,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        blechschmidt: {
            id: 'blechschmidt',
            name: 'Blechschmidt',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            officer: true,
            tokens: {
                ordered: false,
                commanded: true,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        rifleman1: {
            id: 'rifleman1',
            name: 'Rifleman',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            morale: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        rifleman2: {
            id: 'rifleman2',
            name: 'Rifleman',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            morale: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        rifleman3: {
            id: 'rifleman3',
            name: 'Rifleman',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            morale: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        rifleman4: {
            id: 'rifleman4',
            name: 'Rifleman',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            morale: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        rifleman5: {
            id: 'rifleman5',
            name: 'Rifleman',
            nationality: 'GER',
            placement: 'Deployment',
            attack: 1,
            suppress: 1,
            morale: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        linson: {
            id: 'linson',
            name: 'Linson',
            nationality: 'GER',
            placement: 'Reinforcement',
            attack: 1,
            suppress: 2,
            reinforcement: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        wegscheider: {
            id: 'wegscheider',
            name: 'Wegscheider',
            nationality: 'GER',
            placement: 'Reinforcement',
            attack: 1,
            suppress: 2,
            officer: true,
            reinforcement: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        waltl: {
            id: 'waltl',
            name: 'Waltl',
            nationality: 'AUS',
            placement: 'Reinforcement',
            attack: 1,
            suppress: 2,
            reinforcement: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: null,
        },
        clemenceau: {
            id: 'clemenceau',
            name: 'Clemenceau',
            nationality: 'FRA',
            placement: 'Cellar',
            attack: 0,
            suppress: 1,
            inspire: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'G3',
        },
        gamelin: {
            id: 'gamelin',
            name: 'Gamelin',
            nationality: 'FRA',
            placement: 'Cellar',
            attack: 0,
            suppress: 1,
            inspire: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'C1',
        },
        rocque: {
            id: 'rocque',
            name: 'De La Rocque',
            nationality: 'FRA',
            placement: 'Cellar',
            attack: 0,
            suppress: 1,
            inspire: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'C3',
        },
        reynaud: {
            id: 'reynaud',
            name: 'Reynaud',
            nationality: 'FRA',
            placement: 'Cellar',
            attack: 0,
            suppress: 1,
            inspire: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'C4',
        },
        borotra: {
            id: 'borotra',
            name: 'Borotra',
            nationality: 'FRA',
            placement: 'Cellar',
            attack: 0,
            suppress: 1,
            escape: true,
            tokens: {
                ordered: false,
                commanded: false,
                disrupted: false,
            },
            exhausted: false,
            casualty: false,
            tile: 'C5',
        },
    },
    axis: {
        rifleman: {
            id: 'rifleman',
            name: 'Rifleman',
            defense: 3,
            counter: true,
            advance: true,
        },
        scout: {
            id: 'scout',
            name: 'Scout',
            defense: 4,
            counter: true,
            advance: true,
        },
        sturm: {
            id: 'sturm',
            name: 'Sturm',
            defense: 5,
            counter: true,
            advance: true,
        },
        suppressiveFire: {
            id: 'sf',
            name: 'Suppressive Fire',
            disrupt: true,
        },
        sniper: {
            id: 'sniper',
            name: 'Sniper',
            attack: 4,
        },
        machineGun: {
            id: 'mg',
            name: 'Machine Gunner',
            attack: 2,
            defense: 4,
            counter: true,
            disrupt: true,
        },
        mortar: {
            id: 'mortar',
            name: 'Mortar',
            attack: 3,
            defense: 4,
            counter: true,
            disrupt: true,
        },
        flak20: {
            id: 'flak20',
            name: '20mm FLAK 30',
            attack: 2,
            disrupt: true,
        },
        flak88: {
            id: 'flak88',
            name: '88mm FLAK 37',
            attack: 5,
            disrupt: true,
        },
        pak75: {
            id: 'pak75',
            name: '75mm PAK 40',
            attack: 4,
            disrupt: true,
        },
        panzerfaust: {
            id: 'pf',
            name: 'Panzerfaust',
            attack: 4,
        },
    },
};

const reducer = (state = initialState, { type, payload }) => {
    switch (type) {
    case 'RESET_UNITS':
        return {
            ...initialState,
        };
    case 'UPDATE_ALLIES':
        return {
            ...state,
            allies: [...payload],
        };
    default:
        return state;
    }
};

export default reducer;
