const initialState = {
    allies: {
        'Basse': {
            name: 'Basse',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            command: true,
            tanker: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Lee': {
            name: 'Lee',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            command: true,
            tanker: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Worsham': {
            name: 'Worsham',
            nationality: 'USA',
            attack: 1,
            suppress: 1,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Pollock': {
            name: 'Pollack',
            nationality: 'USA',
            attack: 2,
            suppress: 3,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Steiner': {
            name: 'Steiner',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Szymczyk': {
            name: 'Szymczyk',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Rushford': {
            name: 'Rushford',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Schrader': {
            name: 'Schrader',
            nationality: 'SS',
            attack: 1,
            suppress: 2,
            command: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Gangl': {
            name: 'Gangl',
            nationality: 'GER',
            attack: 1,
            suppress: 2,
            command: true,
            officer: true,
            sacrifice: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Dietrich': {
            name: 'Dietrich',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            officer: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'RF1': {
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'RF2': {
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'RF3': {
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'RF4': {
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'RF5': {
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Linson': {
            name: 'Linson',
            nationality: 'GER',
            attack: 1,
            suppress: 2,
            reinforcement: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Waltl': {
            name: 'Waltl',
            nationality: 'AUS',
            attack: 1,
            suppress: 2,
            reinforcement: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Clemenceau': {
            name: 'Clemenceau',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            prisoner: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Gamelin': {
            name: 'Gamelin',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            prisoner: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'De La Rocque': {
            name: 'De La Rocque',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            prisoner: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Reynaud': {
            name: 'Reynaud',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            prisoner: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
        'Borotra': {
            name: 'Borotra',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            escape: true,
            location: null,
            disrupted: false,
            exhausted: false,
        },
    },
    enemies: {
        'Rifleman': {
            defense: 3, 
        },
        'Scout': {
            defense: 4,
        },
        'Sturm': {
            defense: 5,
        },
        'Machine Gunner': {
            attack: 2,
            defense: 4,
            disrupt: true,
        },
        'Mortar': {
            attack: 3,
            defense: 4,
            disrupt: true,
        },
        '20mm FLAK 30': {
            attack: 2,
            disrupt: true,
            target: ['purple', 'red'],
        },
    }
};

const reducer = (state = initialState, { type, payload }) => {
    switch (type) {
    case 'RESET_UNITS':
        return {
            ...initialState,
        }
    default:
        return state;
    }
};

export default reducer;
