const initialState = {
    allies: {
        basse: {
            id: 'basse',
            name: 'Basse',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            commander: true,
            tanker: true,
            ordered: true,
            commanded: false,
            disrupted: false,
            exhausted: true,
            casualty: false,
            tile: 'NT2',
            location: 'NT', // D
        },
        lee: {
            id: 'lee',
            name: 'Lee',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            commander: true,
            tanker: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'NT5',
            location: 'NT5', // D
        },
        worsham: {
            id: 'worsham',
            name: 'Worsham',
            nationality: 'USA',
            attack: 1,
            suppress: 1,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D3',
            location: 'D',
        },
        pollack: {
            id: 'pollack',
            name: 'Pollack',
            nationality: 'USA',
            attack: 2,
            suppress: 3,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'G2',
            location: 'G', // D
        },
        sutton: {
            id: 'sutton',
            name: 'Sutton',
            nationality: 'USA',
            attack: 1,
            suppress: 1,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D5',
            location: 'D',
        },
        petrukovich: {
            id: 'petrukovich',
            name: 'Petrukovich',
            nationality: 'USA',
            attack: 1,
            suppress: 1,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D6',
            location: 'D',
        },
        steiner: {
            id: 'steiner',
            name: 'Steiner',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'BJ1',
            location: 'BJ', // D
        },
        szymczyk: {
            id: 'szymczyk',
            name: 'Szymczyk',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D8',
            location: 'D',
        },
        rushford: {
            id: 'rushford',
            name: 'Rushford',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'BJ3',
            location: 'D',
        },
        mchaley: {
            id: 'mchaley',
            name: 'McHaley',
            nationality: 'USA',
            attack: 1,
            suppress: 2,
            tanker: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D10',
            location: 'D',
        },
        schrader: {
            id: 'schrader',
            name: 'Schrader',
            nationality: 'SS',
            attack: 1,
            suppress: 2,
            commander: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D11',
            location: 'D',
        },
        gangl: {
            id: 'gangl',
            name: 'Gangl',
            nationality: 'GER',
            attack: 1,
            suppress: 2,
            commander: true,
            officer: true,
            sacrifice: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D12',
            location: 'D',
        },
        dietrich: {
            id: 'dietrich',
            name: 'Dietrich',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            officer: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D13',
            location: 'D',
        },
        hockel: {
            id: 'hockel',
            name: 'Hockel',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            officer: true,
            ordered: false,
            commanded: false,
            disrupted: true,
            exhausted: false,
            casualty: false,
            tile: 'D14',
            location: 'D',
        },
        blechschmidt: {
            id: 'blechschmidt',
            name: 'Blechschmidt',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            officer: true,
            ordered: false,
            commanded: true,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D15',
            location: 'D',
        },
        rifleman1: {
            id: 'rifleman1',
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D16',
            location: 'D',
        },
        rifleman2: {
            id: 'rifleman2',
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D17',
            location: 'D',
        },
        rifleman3: {
            id: 'rifleman3',
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D18',
            location: 'D',
        },
        rifleman4: {
            id: 'rifleman4',
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D19',
            location: 'D',
        },
        rifleman5: {
            id: 'rifleman5',
            name: 'Rifleman',
            nationality: 'GER',
            attack: 1,
            suppress: 1,
            morale: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'D20',
            location: 'D',
        },
        wegscheider: {
            id: 'wegscheider',
            name: 'Wegscheider',
            nationality: 'GER',
            attack: 1,
            suppress: 2,
            officer: true,
            reinforcement: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'R1',
            location: 'R',
        },
        linson: {
            id: 'linson',
            name: 'Linson',
            nationality: 'GER',
            attack: 1,
            suppress: 2,
            reinforcement: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'R2',
            location: 'R',
        },
        waltl: {
            id: 'waltl',
            name: 'Waltl',
            nationality: 'AUS',
            attack: 1,
            suppress: 2,
            reinforcement: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'R3',
            location: 'R',
        },
        clemenceau: {
            id: 'clemenceau',
            name: 'Clemenceau',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'C1',
            location: 'C',
        },
        gamelin: {
            id: 'gamelin',
            name: 'Gamelin',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'C2',
            location: 'C',
        },
        rocque: {
            id: 'rocque',
            name: 'De La Rocque',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'C3',
            location: 'C',
        },
        reynaud: {
            id: 'reynaud',
            name: 'Reynaud',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            inspire: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'C4',
            location: 'C',
        },
        borotra: {
            id: 'borotra',
            name: 'Borotra',
            nationality: 'FRA',
            attack: 0,
            suppress: 1,
            escape: true,
            ordered: false,
            commanded: false,
            disrupted: false,
            exhausted: false,
            casualty: false,
            tile: 'C5',
            location: 'C',
        },
    },
    axis: {
        rifleman: {
            id: 'rifleman',
            name: 'Rifleman',
            defense: 3,
            counter: true,
            advance: true,
        },
        scout: {
            id: 'scout',
            name: 'Scout',
            defense: 4,
            counter: true,
            advance: true,
        },
        sturm: {
            id: 'sturm',
            name: 'Sturm',
            defense: 5,
            counter: true,
            advance: true,
        },
        suppressiveFire: {
            id: 'sf',
            name: 'Suppressive Fire',
            disrupt: true,
        },
        sniper: {
            id: 'sniper',
            name: 'Sniper',
            attack: 4,
        },
        machineGun: {
            id: 'mg',
            name: 'Machine Gunner',
            attack: 2,
            defense: 4,
            counter: true,
            disrupt: true,
        },
        mortar: {
            id: 'mortar',
            name: 'Mortar',
            attack: 3,
            defense: 4,
            counter: true,
            disrupt: true,
        },
        flak20: {
            id: 'flak20',
            name: '20mm FLAK 30',
            attack: 2,
            disrupt: true,
        },
        flak88: {
            id: 'flak88',
            name: '88mm FLAK 37',
            attack: 5,
            disrupt: true,
        },
        pak75: {
            id: 'pak75',
            name: '75mm PAK 40',
            attack: 4,
            disrupt: true,
        },
        panzerfaust: {
            id: 'pf',
            name: 'Panzerfaust',
            attack: 4,
        },
    },
};

const reducer = (state = initialState, { type, payload }) => {
    let unit;

    switch (type) {
    case 'RESET_UNITS':
        return {
            ...initialState,
        }
    case 'UPDATE_ALLIES':
        return {
            ...state,
            allies: {
                ...state.allies,
                ...payload,
            },
        }
    case 'TOGGLE_EXHAUSTION':
        unit = state.allies[payload];

        return {
            ...state,
            allies: { 
                ...state.allies,
                [unit.id]: {
                    ...unit,
                    exhausted: !unit.exhausted,
                }
            },
        }
    case 'TOGGLE_DISRUPTED':
        unit = state.allies[payload];

        return {
            ...state,
            allies: {
                ...state.allies,
                [unit.id]: {
                    ...unit,
                    disrupted: !unit.disrupted,
                }
            }
        }
    case 'TOGGLE_ORDERED':
        unit = state.allies[payload];

        return {
            ...state,
            allies: {
                ...state.allies,
                [unit.id]: {
                    ...unit,
                    ordered: !unit.ordered,
                    exhausted: !unit.exhausted,
                }
            }
        }
    case 'TOGGLE_COMMANDED':
        unit = state.allies[payload];

        return {
            ...state,
            allies: {
                ...state.allies,
                [unit.id]: {
                    ...unit,
                    commanded: !unit.commanded,
                    exhausted: false,
                }
            }
        }
    case 'TOGGLE_CASUALTY':
        unit = state.allies[payload];

        return {
            ...state,
            allies: { 
                ...state.allies,
                [unit.id]: {
                    ...unit,
                    casualty: !unit.casualty,
                },
            },
        }
    default:
        return state;
    }
};

export default reducer;
